### ISSUE TITLE
DL_DIR change possibility

### ISSUE THREAD

**Issue by adri1mart1** [cpb-/chef#27]
It would be appreciable to change easily the default DL_DIR path easily. On my computer, I always try to use a single download folder for multiple Yocto directories (Less bandwidth, less used disk spaces, more eco friendly :) )

Change this DL_DIR var in the menu is now really handy as the menu is shared between customers and everyone has it's own custom preferences.

Any suggestions ?

**Comment by cpb-** [comment]
Maybe an attribute in the `.chefconfig` file ?
That one can set with a `chef init --del-dir` option.

**Comment by adri1mart1** [comment]
Yes, that would be nice. I can suggest something based on this if you want
