### ISSUE TITLE
Git submodules are not handled

### ISSUE THREAD

**Issue by pboettch** [cpb-/chef#30]
If a source contains submodules, they need to be updated as well.

**Comment by cpb-** [comment]
We can add `--recurse-submodules` to the `git clone` command line.
Then, if `.gitmodules` is present call `git submodule foreach "git pull"`.
Is this correct?

**Comment by pboettch** [comment]
OK for cloning.

For updating, we need `git submodule update --recursive --init.

**Comment by cpb-** [comment]
Fixed by 58582d01a1c35d9c478772b57ca772ee3f146ceb
