### ISSUE TITLE
[RFC] Versioning

### ISSUE THREAD

**Issue by cpb-** [cpb-/chef#51]
I propose using a kind of semantic versioning for `chef` with three parts version number `XX.YY.ZZ`:

- `XX` is incremented when the compatibility with previous menus is broken. We have to avoid this situation as long as possible.
- `YY` is incremented when a new feature (concerning menus, command-line options, etc.) is added but previous menus still work (ie. `README.md` file needs to be updated but not necessarily sample menus).
- `ZZ` is incremented for bug fixes or internal refactoring that doesn't concern end users (`README.md` file doesn't have to be changed).

We could start with `1.0.0` as soon as the latest pull requests will be integrated and the `README.md` be updated. We also need to add `chef --version` command line option.

Patrick, Adrien(s), are you ok with this ? Do you prefer another approach ?

**Comment by pboettch** [comment]
I like it.
