### ISSUE TITLE
yocto-cooker only support poky based distribution

### ISSUE THREAD

**Issue by RomainNaour** [cpb-/chef#97]
Hello,

I tried to switch an Arago based distribution from oe-layersetup [1] to yocto-cooker but it doesn't work since yocto-cooker really want to use 'poky/oe-init-build-env' script [2]

oe-init-build-env script is imported from oe-core to poky, it should be possible to override DEFAULT_INIT_BUILD_SCRIPT to 'oe-core/oe-init-build-env'.

DEFAULT_INIT_BUILD_SCRIPT = 'poky/oe-init-build-env' 

[1] http://arago-project.org/git/projects/oe-layersetup.git
[2] https://github.com/cpb-/yocto-cooker/blob/master/cooker/cooker.py#L294

Best regards,
Romain

**Comment by RomainNaour** [comment]
I'm ok with your proposal.

So if "init-build-env-script" is not provided in the menu, the "poky/oe-init-build-env" script will be used by default (expecting a poky based distribution) ?

**Comment by cpb-** [comment]
Hi Romain, 

Thanks for pointing us the mistake in my commit. Could you test with the new commit in pull-request #98?

For `DISTRO ?="poky"` it is still present but it's just a default value overriden by `DISTRO='arago'.

I'll have to parse the `local.conf` and add this line only if the `DISTRO` variable is not set. This will be done in a upcoming patch.

**Comment by pboettch** [comment]
Hmm, we should not parse local.conf in Cooker if it cannot be avoided. I'm saying this without understanding the problem.

**Comment by pboettch** [comment]
@cpb- This is fixed with your latest commit (at least), isn't it?
